import createSystem from '../createSystem'

const amountOfSubstanceSystem = createSystem({
  constants: {},
  from: {
    ymol: value => value / 1e24,
    zmol: value => value / 1e21,
    amol: value => value / 1e18,
    fmol: value => value / 1e15,
    pmol: value => value / 1e12,
    nmol: value => value / 1e9,
    µmol: value => value / 1e6,
    mmol: value => value / 1e3,
    cmol: value => value / 100,
    dmol: value => value / 10,
    mol: value => value,
    damol: value => value * 10,
    hmol: value => value * 100,
    kmol: value => value * 1e3,
    Mmol: value => value * 1e6,
    Gmol: value => value * 1e9,
    Tmol: value => value * 1e12,
    Pmol: value => value * 1e15,
    Emol: value => value * 1e18,
    Zmol: value => value * 1e21,
    Ymol: value => value * 1e24,
  },
  to: {
    ymol: value => value * 1e24,
    zmol: value => value * 1e21,
    amol: value => value * 1e18,
    fmol: value => value * 1e15,
    pmol: value => value * 1e12,
    nmol: value => value * 1e9,
    µmol: value => value * 1e6,
    mmol: value => value * 1e3,
    cmol: value => value * 100,
    dmol: value => value * 10,
    mol: value => value,
    damol: value => value / 10,
    hmol: value => value / 100,
    kmol: value => value / 1e3,
    Mmol: value => value / 1e6,
    Gmol: value => value / 1e9,
    Tmol: value => value / 1e12,
    Pmol: value => value / 1e15,
    Emol: value => value / 1e18,
    Zmol: value => value / 1e21,
    Ymol: value => value / 1e24,
  },
  baseUnit: 'mol',
})

export default amountOfSubstanceSystem
