import createSystem from '../createSystem'

const electricCurrentSystem = createSystem({
  constants: {},
  from: {
    yA: value => value / 1e24,
    zA: value => value / 1e21,
    aA: value => value / 1e18,
    fA: value => value / 1e15,
    pA: value => value / 1e12,
    nA: value => value / 1e9,
    µA: value => value / 1e6,
    mA: value => value / 1e3,
    cA: value => value / 100,
    dA: value => value / 10,
    A: value => value,
    daA: value => value * 10,
    hA: value => value * 100,
    kA: value => value * 1e3,
    MA: value => value * 1e6,
    GA: value => value * 1e9,
    TA: value => value * 1e12,
    PA: value => value * 1e15,
    EA: value => value * 1e18,
    ZA: value => value * 1e21,
    YA: value => value * 1e24,
  },
  to: {
    yA: value => value * 1e24,
    zA: value => value * 1e21,
    aA: value => value * 1e18,
    fA: value => value * 1e15,
    pA: value => value * 1e12,
    nA: value => value * 1e9,
    µA: value => value * 1e6,
    mA: value => value * 1e3,
    cA: value => value * 100,
    dA: value => value * 10,
    A: value => value,
    daA: value => value / 10,
    hA: value => value / 100,
    kA: value => value / 1e3,
    MA: value => value / 1e6,
    GA: value => value / 1e9,
    TA: value => value / 1e12,
    PA: value => value / 1e15,
    EA: value => value / 1e18,
    ZA: value => value / 1e21,
    YA: value => value / 1e24,
  },
  baseUnit: 'A',
})

export default electricCurrentSystem
