import createSystem from '../createSystem'

const luminousIntensitySystem = createSystem({
  constants: {},
  from: {
    ycd: value => value / 1e24,
    zcd: value => value / 1e21,
    acd: value => value / 1e18,
    fcd: value => value / 1e15,
    pcd: value => value / 1e12,
    ncd: value => value / 1e9,
    µcd: value => value / 1e6,
    mcd: value => value / 1e3,
    ccd: value => value / 100,
    dcd: value => value / 10,
    cd: value => value,
    dacd: value => value * 10,
    hcd: value => value * 100,
    kcd: value => value * 1e3,
    Mcd: value => value * 1e6,
    Gcd: value => value * 1e9,
    Tcd: value => value * 1e12,
    Pcd: value => value * 1e15,
    Ecd: value => value * 1e18,
    Zcd: value => value * 1e21,
    Ycd: value => value * 1e24,
  },
  to: {
    ycd: value => value * 1e24,
    zcd: value => value * 1e21,
    acd: value => value * 1e18,
    fcd: value => value * 1e15,
    pcd: value => value * 1e12,
    ncd: value => value * 1e9,
    µcd: value => value * 1e6,
    mcd: value => value * 1e3,
    ccd: value => value * 100,
    dcd: value => value * 10,
    cd: value => value,
    dacd: value => value / 10,
    hcd: value => value / 100,
    kcd: value => value / 1e3,
    Mcd: value => value / 1e6,
    Gcd: value => value / 1e9,
    Tcd: value => value / 1e12,
    Pcd: value => value / 1e15,
    Ecd: value => value / 1e18,
    Zcd: value => value / 1e21,
    Ycd: value => value / 1e24,
  },
  baseUnit: 'cd',
})

export default luminousIntensitySystem
