import createSystem from '../createSystem'

const massSystem = createSystem({
  constants: {},
  from: {
    yg: value => value / 1e24,
    zg: value => value / 1e21,
    ag: value => value / 1e18,
    fg: value => value / 1e15,
    pg: value => value / 1e12,
    ng: value => value / 1e9,
    µg: value => value / 1e6,
    mg: value => value / 1e3,
    cg: value => value / 100,
    dg: value => value / 10,
    g: value => value,
    dag: value => value * 10,
    hg: value => value * 100,
    kg: value => value * 1e3,
    Mg: value => value * 1e6,
    Gg: value => value * 1e9,
    Tg: value => value * 1e12,
    Pg: value => value * 1e15,
    Eg: value => value * 1e18,
    Zg: value => value * 1e21,
    Yg: value => value * 1e24,
  },
  to: {
    yg: value => value * 1e24,
    zg: value => value * 1e21,
    ag: value => value * 1e18,
    fg: value => value * 1e15,
    pg: value => value * 1e12,
    ng: value => value * 1e9,
    µg: value => value * 1e6,
    mg: value => value * 1e3,
    cg: value => value * 100,
    dg: value => value * 10,
    g: value => value,
    dag: value => value / 10,
    hg: value => value / 100,
    kg: value => value / 1e3,
    Mg: value => value / 1e6,
    Gg: value => value / 1e9,
    Tg: value => value / 1e12,
    Pg: value => value / 1e15,
    Eg: value => value / 1e18,
    Zg: value => value / 1e21,
    Yg: value => value / 1e24,
  },
  baseUnit: 'g',
})

export default massSystem
