import createSystem from '../createSystem'

const temperatureSystem = createSystem({
  constants: {},
  from: {
    yK: value => value / 1e24,
    zK: value => value / 1e21,
    aK: value => value / 1e18,
    fK: value => value / 1e15,
    pK: value => value / 1e12,
    nK: value => value / 1e9,
    µK: value => value / 1e6,
    mK: value => value / 1e3,
    cK: value => value / 100,
    dK: value => value / 10,
    K: value => value,
    daK: value => value * 10,
    hK: value => value * 100,
    kK: value => value * 1e3,
    MK: value => value * 1e6,
    GK: value => value * 1e9,
    TK: value => value * 1e12,
    PK: value => value * 1e15,
    EK: value => value * 1e18,
    ZK: value => value * 1e21,
    YK: value => value * 1e24,
    '°C': value => value + 273.15,
    '°F': value => (value + 459.67) * (5 / 9),
    '°R': value => value * (5 / 9),
  },
  to: {
    yK: value => value * 1e24,
    zK: value => value * 1e21,
    aK: value => value * 1e18,
    fK: value => value * 1e15,
    pK: value => value * 1e12,
    nK: value => value * 1e9,
    µK: value => value * 1e6,
    mK: value => value * 1e3,
    cK: value => value * 100,
    dK: value => value * 10,
    K: value => value,
    daK: value => value / 10,
    hK: value => value / 100,
    kK: value => value / 1e3,
    MK: value => value / 1e6,
    GK: value => value / 1e9,
    TK: value => value / 1e12,
    PK: value => value / 1e15,
    EK: value => value / 1e18,
    ZK: value => value / 1e21,
    YK: value => value / 1e24,

    '°C': value => value - 273.15,
    '°F': value => value * (9 / 5) - 459.67,
    '°R': value => value * (9 / 5),
  },
  baseUnit: 'K',
})

export default temperatureSystem
