import createSystem from '../createSystem'

const timeSystem = createSystem({
  constants: {},
  from: {
    ys: value => value / 1e24,
    zs: value => value / 1e21,
    as: value => value / 1e18,
    fs: value => value / 1e15,
    ps: value => value / 1e12,
    ns: value => value / 1e9,
    µs: value => value / 1e6,
    ms: value => value / 1e3,
    cs: value => value / 100,
    ds: value => value / 10,
    s: value => value,
    das: value => value * 10,
    hs: value => value * 100,
    ks: value => value * 1e3,
    Ms: value => value * 1e6,
    Gs: value => value * 1e9,
    Ts: value => value * 1e12,
    Ps: value => value * 1e15,
    Es: value => value * 1e18,
    Zs: value => value * 1e21,
    Ys: value => value * 1e24,

    m: value => value * 60,
    h: value => value * 3600,
    d: value => value * 86400,
    w: value => value * 604800,
    M: value => value * 2592000,
    y: value => value * 31536000,
  },
  to: {
    ys: value => value * 1e24,
    zs: value => value * 1e21,
    as: value => value * 1e18,
    fs: value => value * 1e15,
    ps: value => value * 1e12,
    ns: value => value * 1e9,
    µs: value => value * 1e6,
    ms: value => value * 1e3,
    cs: value => value * 100,
    ds: value => value * 10,
    s: value => value,
    das: value => value / 10,
    hs: value => value / 100,
    ks: value => value / 1e3,
    Ms: value => value / 1e6,
    Gs: value => value / 1e9,
    Ts: value => value / 1e12,
    Ps: value => value / 1e15,
    Es: value => value / 1e18,
    Zs: value => value / 1e21,
    Ys: value => value / 1e24,

    m: value => value / 60,
    h: value => value / 3600,
    d: value => value / 86400,
    w: value => value / 604800,
    M: value => value / 2592000,
    y: value => value / 31536000,
  },
  baseUnit: 's',
})

export default timeSystem
