name: On Main Push

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release Packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          cache: yarn
      - name: Configure NX Caches
        uses: nrwl/nx-set-shas@v2
      - name: Authenticate NPM Registries
        run: |
          npm config set "@stackmeister:registry" "https://registry.npmjs.org/"
          npm config set "//registry.npmjs.org/:_authToken" "${{ secrets.PUBLIC_NPM_REGISTRY_TOKEN }}"
          npm config set "//registry.npmjs.org/:always-auth" "true"
      - name: Install Dependencies
        run: yarn
      - name: Build Changed Packages
        run: yarn build:all
      - name: Release Changed Packages
        run: |
          yarn lerna publish from-package --yes
          exit 0
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PUBLIC_NPM_REGISTRY_TOKEN }}
